services:
  test:
    image: node:22-alpine
    command: sh -c "npm install && npm run build && npm run test"
    working_dir: /usr/src/app
    ports:
      - 9227:9227 # debug
    volumes:
      # use local files as source
      - .:/usr/src/app
    environment:
      NODE_ENV: test
      REDIS_URL: redis://redis
    # waits for redis to start
    depends_on:
      redis:
        condition: service_healthy
    # colorizes output
    tty: true

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping']
      interval: 1s
      timeout: 3s
      retries: 5

volumes:
  node_modules:
